name: CI Pipeline - Hackathon Dados

# Define os gatilhos que iniciam o workflow.
on:
  push:
    branches: [ "develop" ] # Roda em pushes para a branch 'develop'.
  
  pull_request:
    branches: [ "master" ] # Roda em pull requests direcionados à 'master'.

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # Ativa o cache de dependências do pip para acelerar builds futuros.

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes com Pytest
        run: pytest

      # Este passo só é executado se os testes passarem com sucesso.
      - name: Executar pipeline de dados (Bronze, Silver, Gold)
        run: python pipelines/run_all.py

      # Salva a pasta 'data' como um artefato do build.
      # Útil para depuração e verificação dos dados gerados.
      - name: Salvar artefatos de dados
        uses: actions/upload-artifact@v4
        with:
          name: camadas-de-dados
          path: data/